transform:
  height: 34
  width: 34
  raw_size: True
#  denoise:
#    {filter_time: 10000}
  shift:
    {"max_shift": 5}
  sample:
    {window: 1024}
  flip:
    {"p": 0.5}
  toImage:
    type: 'histogram'

dataset:
  name: 'NMNISTProcessed'
  dataset_path: "data/preprocess_h5/NMNIST_window20w_overlap0p5"
  object_classes: 'all'

model:
  model_name: 'mink_mobilenetv2_quant'
  width_mult: 1.0
optim:
  optimizer: 'sgd'
  batch_size: 256
  init_lr: 0.001
  steps_lr: 30
  factor_lr: 0.1
hardware:
  # num_cpu_workers: {-1: auto, 0: main thread, >0: ...}
  num_cpu_workers: 4
  gpu_device: 0  # [0 or 'cpu']
