transform:
  height: 128
  width: 128
  raw_size: True
#  denoise:
#    {filter_time: 0.1}
  shift:
    {"max_shift": 20}
  sample:
    {window: 2048}
  flip:
    {"p": 0}
  toImage:
    {type: 'histogram'}

dataset:
  name: 'DVS_slice'
  dataset_path: "data/DVS_slice/"
  object_classes: 'all'


model:
  model_name: 'mink_mobilenetv2_quant'
  width_mult: 0.5
optim:
  optimizer: 'sgd'
  batch_size: 64
  init_lr: 0.1
  steps_lr: 30
  factor_lr: 0.1
hardware:
  # num_cpu_workers: {-1: auto, 0: main thread, >0: ...}
  num_cpu_workers: 4
  gpu_device: 0  # [0 or 'cpu']
