transform:
  height: 180
  width: 240
  raw_size: True
#  denoise:
#    {filter_time: 0.1}
  shift:
    {"max_shift": 20}
  sample:
    {window: 512, sample_type: 'random'}
  flip:
    {"p": 0.5}
  toImage:
    {type: 'histogram'}

dataset:
  name: 'ASLDVS'
  dataset_path: "data/ASLDVS"
  object_classes: 'all'


model:
  # ['fb_sparse_vgg', 'dense_vgg', 'fb_sparse_object_det', 'dense_object_det', 'fb_sparse_mobilenetv2']
  model_name: 'mink_mobilenetv2_quant'
  width_mult: 1.0
  model_type: models/model_cfg/ASL_2929.json
#  drop_config: { type: "abs_sum_momentum", thresh: 0.1 }
optim:
  optimizer: 'sgd'
  batch_size: 128
  init_lr: 0.001
  # Set to "steps: ~" if no scheduler is needed
  steps_lr: 30
  factor_lr: 0.1
hardware:
  # num_cpu_workers: {-1: auto, 0: main thread, >0: ...}
  num_cpu_workers: 4
  gpu_device: 0  # [0 or 'cpu']
