transform:
  height: 128
  width: 128
  raw_size: True
#  denoise:
#    {filter_time: 10000}
  shift:
    { "max_shift": 20 }
  sample:
    {window: 4096, sample_type: "random"}
  flip:
    {"p": 0}
  toImage:
    type: 'histogram'

dataset:
  # 'NCaltech101' or 'NCaltech101_ObjectDetection', 'Prophesee', 'NCars'
  name: 'DVSGesture_processed'
  dataset_path: "/home/user/Documents/event_dataset_preprocessed/dvs_gesture_clip"
  object_classes: 'all'


dir:
  log: 'log/'
model:
  # ['fb_sparse_vgg', 'dense_vgg', 'fb_sparse_object_det', 'dense_object_det', 'fb_sparse_mobilenetv2']
  model_name: 'mink_mobilenetv2'
  width_mult: 1.0
  drop_config: { type: "abs_sum_momentum", stages: [ 1,2,3,4 ], thresh: [0.2, 0.2, 0.2, 0.2]}
optim:
  optimizer: 'sgd'
  batch_size: 48
  init_lr: 0.1
  # Set to "steps: ~" if no scheduler is needed
  steps_lr: 30
  factor_lr: 0.1
checkpoint:
  resume_training: True
  resume_file: ''
  # Networks trained for classification can be reused as starting point for object detection networks on trained
  # the same dataset
  use_pretrained: False
  pretrained_dense_vgg: ''
  pretrained_sparse_vgg: ''
hardware:
  # num_cpu_workers: {-1: auto, 0: main thread, >0: ...}
  num_cpu_workers: 4
  gpu_device: 0  # [0 or 'cpu']