artifact_location: /vol/datastore/zhangbh/EyeTracking/exp/0322_fixRNNsearch/cfg205_bit16_fixBN0p3_biasbit16/0
creation_time: 1711178833933
experiment_id: '0'
last_update_time: 1711178833933
lifecycle_stage: active
name: Default
