transform:
  height: 180
  width: 240
  raw_size: True
  denoise:
    {filter_time: -1}
  shift:
    { "max_shift": 20 }
  sample:
    {window: 50000}
  flip:
    {"p": 0.5}
  toImage:
    {type: 'histogram'}

dataset:
  name: 'NCaltech101'
  dataset_path: "data/N-Caltech101"
  object_classes: 'all'


model:
  model_name: 'mink_mobilenetv2'
  width_mult: 1.0
optim:
  optimizer: 'sgd'
  batch_size: 16
  init_lr: 0.1
  steps_lr: 50
  factor_lr: 0.1
hardware:
  # num_cpu_workers: {-1: auto, 0: main thread, >0: ...}
  num_cpu_workers: 0
  gpu_device: 0  # [0 or 'cpu']