artifact_location: /vol/datastore/zhangbh/EyeTracking/exp/0324_fixRNN_optimSearch_quant/cfg858_biasbit16_shift16_fixBN0p6/0
creation_time: 1711253600965
experiment_id: '0'
last_update_time: 1711253600965
lifecycle_stage: active
name: Default
